// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXLv3sLODu4rCgRTIJrBguEXZp7V4ceOs',
    appId: '1:13619847296:web:8e4a36fed145fc8edb0665',
    messagingSenderId: '13619847296',
    projectId: 'voter-list-management-system',
    authDomain: 'voter-list-management-system.firebaseapp.com',
    storageBucket: 'voter-list-management-system.firebasestorage.app',
    measurementId: 'G-606GJWLNW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe8zkOSr6rqrMJlOScMkKvgYbMw_kxSnk',
    appId: '1:13619847296:android:3c08500567f67b9edb0665',
    messagingSenderId: '13619847296',
    projectId: 'voter-list-management-system',
    storageBucket: 'voter-list-management-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfwL-XnaKgBxRiOKqgUzTn_rqOqAlqWY',
    appId: '1:13619847296:ios:fa43e5b495654c8adb0665',
    messagingSenderId: '13619847296',
    projectId: 'voter-list-management-system',
    storageBucket: 'voter-list-management-system.firebasestorage.app',
    iosBundleId: 'com.example.pollingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfwL-XnaKgBxRiOKqgUzTn_rqOqAlqWY',
    appId: '1:13619847296:ios:fa43e5b495654c8adb0665',
    messagingSenderId: '13619847296',
    projectId: 'voter-list-management-system',
    storageBucket: 'voter-list-management-system.firebasestorage.app',
    iosBundleId: 'com.example.pollingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXLv3sLODu4rCgRTIJrBguEXZp7V4ceOs',
    appId: '1:13619847296:web:5299d708ea6a9dc2db0665',
    messagingSenderId: '13619847296',
    projectId: 'voter-list-management-system',
    authDomain: 'voter-list-management-system.firebaseapp.com',
    storageBucket: 'voter-list-management-system.firebasestorage.app',
    measurementId: 'G-T8FTQPG7CV',
  );
}
